services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: bukowski
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql # Mounting the volume here
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: "user:pass@tcp(db:3306)/bukowski?parseTime=true"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: # Defining the named volume
